136 bug make calendar fit screen size
cse110-fa22-group32/cse110-fa22-group32 pull request #147
Opened 2022-12-05 00:40 UTC by jonathaanh

2022-12-05 00:48 UTC, jonathaanh commented
I did not end up fixing the calendar dimensions because I didn't want to mess with too many variables, and the smaller screen also just looked worse. I added the styling for the two modals, and fixed the text alignment for the footer section. Also, changed the margin top and bottom for the side panel to match the calendar.

2022-12-05 01:10 UTC, jonathaanh commented
The codacy error doesn't make sense

2022-12-05 10:45 UTC, stevenkhaw requested changes
changes look good, can u just run prettier js and/or stylelint on CSS

2022-12-06 05:05 UTC, stevenkhaw approved these changes

2022-12-06 05:05 UTC, merged